name: CI for PHP 7.1 backport

on:
  push:
    branches: [ PHP-7.1 ]
  pull_request:
    branches: [ PHP-7.1 ]

jobs:
  build:
    env:
      CFLAGS: -fno-strict-aliasing -Wno-pointer-sign

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: PHP-7.1
    - name: get devel packages
      run: sudo apt-get -y install libpng-dev libfreetype6-dev libxpm-dev libbz2-dev libcurl4-openssl-dev libssl-dev libsqlite3-dev zlib1g-dev libpcre3-dev libkrb5-dev libedit-dev libxml2-dev libc-client2007e-dev libsasl2-dev postgresql-server-dev-all unixodbc-dev libsnmp-dev libxslt-dev libjpeg-dev libwebp-dev libgd3 re2c bison

    - name: configure
      run: |
        touch configure.in
        ./buildconf --force
        ./configure  --prefix=/usr  --sysconfdir=/etc  --with-libdir=lib64  --with-config-file-path=/etc  --with-config-file-scan-dir=/etc/php56.d  --disable-debug  --with-pic  --disable-rpath  --without-pear  --with-freetype-dir=/usr  --with-png-dir=/usr  --with-xpm-dir=/usr  --enable-gd-native-ttf  --without-gdbm  --with-jpeg-dir=/usr  --with-openssl  --with-system-ciphers  --with-pcre-regex  --with-zlib  --with-layout=GNU  --with-kerberos  --with-libxml-dir=/usr  --with-mhash  --libdir=/usr/lib64/php  --enable-pcntl  --enable-opcache  --enable-phpdbg  --with-imap=shared --with-imap-ssl  --enable-mbstring=shared  --enable-mbregex  --with-gd=shared  --with-gmp=shared  --enable-calendar=shared  --enable-bcmath=shared  --with-bz2=shared  --enable-ctype=shared  --enable-dba=shared --with-db4=/usr  --with-tcadb=/usr  --enable-exif=shared  --enable-ftp=shared  --with-gettext=shared

    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
